[workers]
# Replace with Terraform output value.
worker ansible_host=192.168.150.10

[db]
# Replace with Terraform output value.
db ansible_host=192.168.150.11

[all:vars]
ansible_user=ansible
ansible_python_interpreter=/usr/bin/python3
